// TODO: rename to NotificationType when already refactored
enum NotificationNewType {
  notifikasi_jam_istirahat,
  notifikasi_jam_pulang,
  notifikasi_cuti_diajukan,
  notifikasi_cuti_diterima,
  notifikasi_cuti_ditolak,
  notifikasi_task_from_admin,
  notifikasi_jam_kerja,
  tasks,
  inventaris_service,
  inventaris_pajak,
  inventaris_kontrak_sewa,
  notifikasi_task_cancel_today,
  notifikasi_shift_assigned,
  notifikasi_shift_swap_request,
  notifikasi_shift_swap_approved,
  notifikasi_shift_swap_rejected,
  notifikasi_shift_swap_expired,
  notifikasi_punishment_added,
  notifikasi_punishment_deleted,
  notifikasi_purchase_order_diajukan,
  unknown,
}
